modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/Luke100000/ImmersivePillagers/issues"
license = "GPL-3.0-only"

[[mods]]
modId = "immersive_pillagers"
version = "${version}"
displayName = "Immersive Pillagers"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/immersive-pillagers"
authors = "Luke100000"
description = "Let the pillagers attack more creatively!"
logoFile = "icon.png"
itemIcon = "minecraft:crossbow"

[[dependencies.immersive_pillagers]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.immersive_pillagers]]
modId = "forge"
mandatory = true
versionRange = "[1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.immersive_pillagers]]
modId = "immersive_aircraft"
mandatory = true
versionRange = "[1.0.2,)"
ordering = "NONE"
side = "BOTH"