modLoader = "javafml"
loaderVersion = "[${loader_major},)"
issueTrackerURL = "https://github.com/Luke100000/ImmersivePillagers/issues"
license = "GPL-3.0-only"

[[mods]]
modId = "immersive_pillagers"
version = "${version}"
displayName = "Immersive Pillagers"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/immersive-pillagers"
authors = "Luke100000"
description = "Let the pillagers attack more creatively!"
logoFile = "icon.png"
itemIcon = "minecraft:crossbow"

[[dependencies.immersive_pillagers]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.immersive_pillagers]]
modId = "forge"
mandatory = true
versionRange = "[${loader_major},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.immersive_pillagers]]
modId = "immersive_aircraft"
mandatory = false
versionRange = "${immersive_aircraft_version_range}"
ordering = "AFTER"
side = "BOTH"

[[dependencies.immersive_pillagers]]
modId = "immersive_melodies"
mandatory = false
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"
