plugins {
    id "fabric-loom" version "1.14.10" apply false
    id "net.neoforged.moddev" version "2.0.123" apply false
}

def getAppVersion = { ->
    try {
        def tag = providers.exec {
            commandLine "git", "tag", "--points-at", "HEAD"
        }.standardOutput.asText.get().trim()
        return tag.endsWith("+${minecraft_version}") ? tag : "${minecraft_version}-SNAPSHOT"
    } catch (Exception exception) {
        logger.warn("Could not determine the version from Git", exception)
        return "${minecraft_version}-DEV"
    }
}

allprojects {
    group = group_id
    version = getAppVersion()

    repositories {
        maven { url = uri("https://api.modrinth.com/maven") }
        maven { url = uri("https://maven.shedaniel.me/") }
        maven { url = uri("https://maven.terraformersmc.com/releases/") }
        maven { url = uri("https://nexus.resourcefulbees.com/repository/maven-public/") }
        maven { url = uri("https://maven.teamresourceful.com/repository/maven-public/") }
    }
}
