plugins {
    id "net.fabricmc.fabric-loom" version "1.15.5" apply false
    id "net.neoforged.moddev" version "2.0.141" apply false
}

def getAppVersion = { ->
    try {
        def tag = providers.exec {
            commandLine "git", "tag", "--points-at", "HEAD"
        }.standardOutput.asText.get().trim()
        return tag.isEmpty() ? "${minecraft_version}-SNAPSHOT" : tag
    } catch (Exception exception) {
        logger.warn("Could not determine the version from Git", exception)
        return "${minecraft_version}-DEV"
    }
}

allprojects {
    version = getAppVersion()
    group = rootProject.group_id

    repositories {
        maven { url = uri("https://maven.conczin.net/Artifacts") }
    }

}

subprojects {
    plugins.withId("maven-publish") {
        publishing {
            repositories {
                maven {
                    name = "reposiliteRepository"
                    url = uri("https://maven.conczin.net/Artifacts")
                    credentials {
                        username = System.getenv("MAVEN_USERNAME")
                        password = System.getenv("MAVEN_TOKEN")
                    }
                }
            }
        }
    }
}
