plugins {
    id "fabric-loom" version "1.9-SNAPSHOT" apply false
    id "net.neoforged.moddev.legacyforge" version "2.0.77" apply false
}

def getAppVersion = { ->
    try {
        def stdout = new ByteArrayOutputStream()
        exec {
            commandLine "git", "tag", "--points-at", "HEAD"
            standardOutput = stdout
        }
        def tag = stdout.toString().trim()
        return tag.isEmpty() ? "${minecraft_version}-SNAPSHOT" : tag
    } catch (Exception exception) {
        logger.warn("Could not determine the version from Git", exception)
        return "${minecraft_version}-DEV"
    }
}

allprojects {
    group = group_id
    version = getAppVersion()

    repositories {
        maven { url = uri("https://api.modrinth.com/maven") }
        maven { url = uri("https://maven.shedaniel.me/") }
        maven { url = uri("https://maven.terraformersmc.com/releases/") }
        maven { url = uri("https://nexus.resourcefulbees.com/repository/maven-public/") }
        maven { url = uri("https://maven.teamresourceful.com/repository/maven-public/") }
        maven { url = uri("https://dvs1.progwml6.com/files/maven/") }
    }
}
