org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

java_version=25
minecraft_version=26.1.2
minecraft_version_range=[26.1.2,26.2)
fabric_minecraft_version_range=26.1.2
neo_form_version=26.1.2-1

mod_version=26.1.2-SNAPSHOT
mod_id=immersive_pillagers
mod_name=Immersive Pillagers
mod_author=Luke100000
group_id=net.conczin
license=GPL-3.0-only
credits=
description=Let the pillagers attack more creatively!
archives_base_name=immersive_pillagers

fabric_loader_version=0.18.4
fabric_loader_version_range=>=0.18.4
fabric_api_version=0.153.0+26.1.2

neoforge_version=26.1.2.22-beta
neoforge_loader_version_range=[4,)

immersive_aircraft_version_range=[0,)
fabric_immersive_aircraft_version_range=*
