org.gradle.jvmargs=-Xmx3G

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
fabric_minecraft_version_range=~1.20.1
parchment_version=2023.09.03
enabled_platforms=fabric,forge

archives_base_name=immersive_pillagers
group_id=net.conczin

fabric_loader_version=0.16.10
fabric_loader_version_range=>=0.16.10
fabric_api_version=0.92.9+1.20.1

forge_version=1.20.1-47.4.20

immersive_aircraft_version=1.20.1-SNAPSHOT
immersive_aircraft_version_range=[1.0.2,)
fabric_immersive_aircraft_version_range=>=1.0.2
immersive_melodies_version=1.20.1-SNAPSHOT
