org.gradle.jvmargs=-Xmx3G

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
fabric_minecraft_version_range=~1.20.1
parchment_version=2023.09.03
parchment_minecraft=1.20.1
java_version=17

archives_base_name=immersive_pillagers
group_id=net.conczin
mod_id=immersive_pillagers
mod_name=Immersive Pillagers
mod_author=Luke100000
license=GPL-3.0-only
credits=
description=Face pillager hordes, explore hostile camps and lost labs, battle undead illagers, and uncover the secrets of the totem.

fabric_loader_version=0.16.10
fabric_loader_version_range=>=0.16.10
fabric_version=0.92.9+1.20.1

forge_version=47.4.20
forge_loader_version_range=[47,)

immersive_aircraft_version=1.4.1+1.20.1
immersive_aircraft_version_range=[1.4.1,1.5)
fabric_immersive_aircraft_version_range=>=1.4.1 <1.5
immersive_melodies_version=0.7.0+1.20.1
