modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/Luke100000/ImmersivePillagers/issues"
license = "GPL-3.0-only"

[[mixins]]
config = "immersive_pillagers.mixins.json"

[[mixins]]
config = "immersive_pillagers-common.mixins.json"

[[mods]]
modId = "immersive_pillagers"
version = "${version}"
displayName = "Immersive Pillagers"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/immersive-pillagers"
authors = "Luke100000"
description = "Let the pillagers attack more creatively!"
logoFile = "icon.png"
itemIcon = "minecraft:crossbow"

[[dependencies.immersive_pillagers]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.immersive_pillagers]]
modId = "neoforge"
type = "required"
versionRange = "${neoforge_loader_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.immersive_pillagers]]
modId = "immersive_aircraft"
type = "optional"
versionRange = "${immersive_aircraft_version_range}"
ordering = "AFTER"
side = "BOTH"

[[dependencies.immersive_pillagers]]
modId = "immersive_melodies"
type = "optional"
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"
