plugins {
    id "multiloader-loader"
    id "net.neoforged.moddev"
}

neoForge {
    version = neoforge_version
    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})"
        }
        client {
            client()
            gameDirectory = this.mkdir(this.file('runs/client'))
        }
        data {
            clientData()
            gameDirectory = this.mkdir(this.file('runs/data'))
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }
        server {
            server()
            gameDirectory = this.mkdir(this.file('runs/server'))
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

def loaderAttribute = Attribute.of("io.github.mcgradleconventions.loader", String)
["apiElements", "runtimeElements", "sourcesElements"].each { variant ->
    configurations.named(variant) {
        attributes {
            attribute(loaderAttribute, "neoforge")
        }
    }
}
sourceSets.configureEach {
    [it.compileClasspathConfigurationName, it.runtimeClasspathConfigurationName, it.getTaskName(null, "jarJar")].each { variant ->
        configurations.named(variant) {
            attributes {
                attribute(loaderAttribute, "neoforge")
            }
        }
    }
}

tasks.withType(JavaExec).configureEach {
    jvmArgs("-Xmx3G")
}

processResources {
    inputs.properties(version: project.version, minecraft_version_range: minecraft_version_range,
            immersive_aircraft_version_range: immersive_aircraft_version_range,
            neoforge_loader_version_range: neoforge_loader_version_range)
    filesMatching("META-INF/neoforge.mods.toml") {
        expand(version: project.version, minecraft_version_range: minecraft_version_range,
                immersive_aircraft_version_range: immersive_aircraft_version_range,
                neoforge_loader_version_range: neoforge_loader_version_range)
    }
}
